spring:
  data:
    mongodb:
      host: 192.168.136.104
      port: 27017
      database: spitdb
  application:
    name: tensquare-spit
  redis:
    host: 192.168.136.104
    port: 6379
server:
  port: 9006
jwt:
  config:
    key: imxushuai