server: 
  port: 9004
spring: 
  application:  
    name: tensquare-article #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.136.104:3306/tensquare_article?characterEncoding=UTF8
    username: root
    password: 123456
  redis:
    host: 192.168.136.104
  jpa: 
    database: MySQL
    show-sql: true
  data:
    mongodb:
      host: 192.168.136.104
      port: 27017
      database: commentdb
jwt:
  config:
    key: imxushuai